window.lan_data = {
    "login_card": "Please enter the card code to register (skip if already activated)",
    "login_pwd": "Please enter password",
    "login_name": "Please enter account",
    "login_elink": "Choose network card adapter",
    "player_setting": "Player settings",
    "show_player_equipment": "Show player's equipment",
    "show_green_on_mount_in_danger": "Show green when in danger while on mount",
    "red_black_area_enemy_sound_alert": "Enemy sound alert in red/black zone (F7 shortcut)",
    "friend_unit_setting": "Friendly unit settings",
    "block_teammate_alliance": "Block teammate/alliance",
    "cave_setting": "Cave settings",
    "show_common_cave": "Show common caves",
    "show_rare_cave": "Show rare caves",
    "monster_setting": "Monster settings",
    "show_common_monster": "Show common monsters",
    "show_resource_monster": "Show resource monsters",
    "show_rare_monster": "Show rare monsters (Enchant quality >1)",
    "close_monster_name_display": "Turn off monster name display",
    "show_mist_spirit": "Show fog spirits",
    "show_cage_monster": "Show lantern monsters",
    "resource_setting": "Resource settings",
    "resource_type": "Resource type",
    "stone": "Stone",
    "mineral": "Ore",
    "wood": "Wood",
    "cotton": "FIBER",
    "leather": "HIDE",
    "resource_level": "Resource level",
    "on": "on",
    "off": "off",
    "up": "UP",
    "down": "Down",
    "ip": "intensity",
    "all": "All",
    "show_resources_above_zero": "Show resources with quantity above 0",
    "block_resource_list": "Block resource list",
    "white_resource_list": "Whitelist resource list",
    "radar": "Radar",
    "radar_setting": "Radar parameter settings",
    "set_top": "Top",
    "software_window_top": "pin window to top",
    "opticate_mode": "transparent mode",
    "cross_window": "window penetration : F6 shortcut",
    "tip_player_sound": "enemy alert sound : F7 shortcut",
    "invite_rewards": "Invitation",
    "backpack_display_down": "move equipment display down",
    "opacity": "opacity",
    "submit_log": "Submit log",
    "Invite_bind": "Invite bind",
    "Invite_information": "Invite Information",
    "Invite_id": "Invite ID：",
    "Invite_information1": "Invitation rules: Receive benefits (limited to monthly card) after filling in the inviter's ID.",
    "Invite_information2": "Inviter: Each time you renew the monthly card, you get an additional 7 days duration.",
    "Invite_information3": "Self: Each time you renew the monthly card, you get an additional 3 days duration.",
    "Rewards_received": "Rewards received",
    "copy_id": "Copy Invite ID",
    "copy_card": "Copy Card info",
    "bind_inviter": "Bind the inviter",
    "current_map": "Current Map",
    "current_speed": "Current Speed",
    "current_tip": "Current tip flag",
    "current_cross": "Current Mouse Cross status",
    "copied_info": "Copied to clipboard",
    "enter_bind_id": "Enter binding ID",
    "rewards_information": "Invitation rewards are available, and some have not been claimed. Please go to the invitation section to retrieve the card code.",
    "not_use": "Not Active",
    "use": "Actived",
    "day": "day",
    "expire_date": "Expire Date",
    "check_lan": "Please select network adapter",
    "check_pwd": "Password cannot be empty",
    "check_user": "Account cannot be empty",
    "had_bind": "Already Bind ID",
    "solo_wisp": "Will o' Wisp",
    "duo_wisp": "Greater Will o' Wisp",
    "avalon_robot": "Avalonian Treasure Drone",
    "roming_chest": "Hidden Treasure",
    "anniversary_place": "Construct of the Ages",
    "might_spider": "Crystal Spiders",
    "mist_dragon": "Fey Dragon",
    "mist_spider": "Veilweaver",
    "mist_griffin": "Griffin",
    "soldier_boss": "Doomed Paragon",
    "personal_spider": "Arcane Spiderlings",
    "corrupted": "Corrupted Dungeon",
    "hellgate2v2": "2v2 Hellgate",
    "groupdungeon": "Group Dungeons",
    "solodungeon": "Solo Dungeons",
    "mob_cage": "Cage Mob",
    "no_data": "No Data",

}
