window.lan_data = {
    "login_card": "请输入卡密注册(已激活可忽略)",
    "login_pwd": "请输入密码",
    "login_name": "请输入账号",
    "login_elink": "选择网卡适配",
    "player_setting": "玩家配置",
    "show_player_equipment": "显示玩家装备",
    "show_green_on_mount_in_danger": "危险区遭遇时在坐骑上显示绿色",
    "red_black_area_enemy_sound_alert": "红黑区遇敌提示音（F7快捷键）",
    "friend_unit_setting": "友方单位配置",
    "block_teammate_alliance": "屏蔽队友/盟友",
    "cave_setting": "洞穴配置",
    "show_common_cave": "显示普通洞穴",
    "show_rare_cave": "显示稀有洞穴",
    "monster_setting": "怪物配置",
    "show_common_monster": "显示普通怪物",
    "show_resource_monster": "显示资源怪物",
    "show_rare_monster": "显示稀有怪物(附魔品质>1)",
    "close_monster_name_display": "关闭怪物名称显示",
    "show_mist_spirit": "显示迷雾精灵",
    "show_cage_monster": "显示灯笼怪",
    "resource_setting": "物资配置",
    "resource_type": "物资类型",
    "stone": "石头",
    "mineral": "矿物",
    "wood": "树木",
    "cotton": "棉花",
    "leather": "皮革",
    "resource_level": "物资等级",
    "on": "开启",
    "off": "关闭",
    "up": "骑乘",
    "down": "下马",
    "ip": "强度",
    "all": "全部",
    "show_resources_above_zero": "显示数量在0以上的资源",
    "block_resource_list": "屏蔽物资列表",
    "white_resource_list": "白名单物资列表",
    "radar": "雷达",
    "radar_setting": "雷达参数设置",
    "set_top": "置顶",
    "software_window_top": "置顶",
    "opticate_mode": "透明模式",
    "cross_window": "窗口穿透 : F6快捷键",
    "tip_player_sound": "遇敌提示音 : F7快捷键",
    "invite_rewards": "邀请奖励",
    "backpack_display_down": "装备显示下移",
    "opacity": "透明度",
    "submit_log": "上传日志",
    "Invite_bind": "邀请绑定",
    "Invite_information": "邀请信息",
    "Invite_id": "邀请ID：",
    "Invite_information1": "受邀规则：填写邀请人ID后获得福利（仅限月卡）",
    "Invite_information2": "邀请人：每次续费月卡可获得7天时长",
    "Invite_information3": "本人：每次续费月卡可获得3天时长",
    "Rewards_received": "已获得的奖励",
    "copy_id": "复制邀请ID",
    "copy_card": "复制卡密",
    "bind_inviter": "绑定邀请人",
    "current_map": "当前地图",
    "current_speed": "当前速度",
    "current_tip": "当前提示音",
    "current_cross": "当前鼠标穿透",
    "copied_info": "已粘贴到剪贴版",
    "enter_bind_id": "输入绑定ID",
    "rewards_information": "邀请奖励存在奖励未领取，前往邀请领取卡密",
    "not_use": "未使用",
    "use": "已使用",
    "day": "天",
    "expire_date": "到期时间",
    "check_lan": "请选择网卡适配器",
    "check_pwd": "密码不能为空",
    "check_user": "账号不能为空",
    "had_bind": "已绑定ID",
    "solo_wisp": "鬼火",
    "duo_wisp": "大鬼火",
    "avalon_robot":"阿瓦隆探宝无人机",
    "roming_chest":"隐藏宝藏",
    "anniversary_place":"纪元造物",
    "might_spider":"水晶蜘蛛",
    "mist_dragon":"妖精龙",
    "mist_spider":"织纱者",
    "mist_griffin":"狮鹫",
    "soldier_boss":"无名英雄",
    "personal_spider":"奥术小蜘蛛",
    "corrupted":"腐蚀地下城",
    "hellgate2v2":"2v2炼狱之门",
    "groupdungeon":"团队地下城",
    "solodungeon":"单人地下城",
    "mob_cage":"灯笼怪",
}





